version: "3.7"
services:
  sonarqube:
    container_name: sonarqube
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile
      network: host
    ports:
      - 9000:9000
    networks:
      - backend

networks:
  backend:
    driver: "bridge"